[tools]
[tools.go]
version = "latest"
postinstall = "go mod download"
pitchfork = "latest"

[tasks.youtube]
alias = "yt"
run = "go run cmd/main.go"
dir = "{{config_root}}"
env = { PORT = 8363, DATABASE_FILE_PATH = "{{vars.couch}}.db", EDITOR_MODE = "full" }

# opens the localhost address in default browser
[tasks.open]
run = "xdg-open http://localhost:8363"
run_windows = "start http://localhost:8363"
alias = "o"
hide = true

# opens browser, starts server in background
[tasks.start]
depends = ["open", "yt"]
alias = "s"

# kills the server running on port 8363
[tasks.kill]
run = "pkill -f 'cmd/main.go' || fuser -k 8363/tcp"
run_windows = "taskkill /F /IM main.exe"
hide = true

[vars]
couch = "couchtube"
